### ISSUE TITLE
Issues Building It on Nodejs Enviroment

### ISSUE THREAD

**Issue by ygorcarmo** [statelyai/sky#28]
repo: [https://github.com/ygorcarmo/sky-sample](link)

error: 
```
[vite] Error when evaluating SSR module /src/trafficLightActor.ts: failed to import "@statelyai/sky"
|- Error [ERR_REQUIRE_ESM]: require() of ES Module /projects/vite-express/node_modules/superjson/dist/index.js from /home/ygorc/projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js not supported.
Instead change the require of index.js in /projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js:6:17)

9:28:17 PM [vite] Error when evaluating SSR module ./src/app.ts: failed to import "/src/trafficLightActor.ts"
|- Error [ERR_REQUIRE_ESM]: require() of ES Module /projects/vite-express/node_modules/superjson/dist/index.js from /projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js not supported.
Instead change the require of index.js in /projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/projects/vite-express/node_modules/@statelyai/sky/dist/statelyai-sky.cjs.js:6:17)
```

**Comment by mellson** [comment]
Hi @ygorcarmo, sorry for the late reply. Is this still something you need help with?
